version: 2

updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore(deps:github):"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
    labels:
      - "dependencies"

  # Composer updates
  - package-ecosystem: "composer"
    directory: "/"
    versioning-strategy: increase
    commit-message:
      prefix: "chore(deps:composer):"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
    labels:
      - "php"
      - "dependencies"

  # npm updates
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: increase
    commit-message:
      prefix: "chore(deps:npm):"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
    labels:
      - "npm"
      - "dependencies"
